mutation userAddressCreate($input: AddressInput!, $type: AddressTypeEnum) {
	accountAddressCreate(type: $type, input: $input) {
		user {
			...UserDetails
		}
		errors {
			field
			message
			code
		}
		address {
			...Address
		}
	}
}

mutation userAddressUpdate($id: ID!, $input: AddressInput!) {
	accountAddressUpdate(id: $id, input: $input) {
		user {
			...UserDetails
		}
		errors {
			field
			message
			code
		}
		address {
			...Address
		}
	}
}

mutation userAddressDelete($id: ID!) {
	accountAddressDelete(id: $id) {
		user {
			...UserDetails
		}
		errors {
			field
			message
			code
		}
		address {
			...Address
		}
	}
}
