fragment Order on Order {
	id
	number
	userEmail
	isPaid
	discounts {
		type
		name
		amount {
			...Money
		}
	}
	chargeStatus
	authorizeStatus
	shippingAddress {
		...Address
	}
	billingAddress {
		...Address
	}
	deliveryMethod {
		...Shipping
	}
	total {
		gross {
			...Money
		}
		tax {
			...Money
		}
	}
	voucher {
		code
	}
	shippingPrice {
		gross {
			...Money
		}
	}
	subtotal {
		gross {
			...Money
		}
	}
	lines {
		...OrderLine
	}
	totalBalance {
		...Money
	}
	totalCaptured {
		...Money
	}
}
