// Link of Channel
const DEFAULT_CHANNEL = process.env.NEXT_PUBLIC_DEFAULT_CHANNEL_SLUG ?? "default-channel";
const PRODUCTS_SLUG = "search";
const ALL_PRODUCTS_SLUG = `/${PRODUCTS_SLUG}`;

const DEFAULT_CHANNEL_SLUG = `/${DEFAULT_CHANNEL}`;
const DEFAULT_CHANNEL_PRODUCTS_SLUG = `${DEFAULT_CHANNEL_SLUG}${ALL_PRODUCTS_SLUG}`;

// Link of Product detail
const RELATED_PRODUCT_SLUG = process.env.NEXT_PUBLIC_RELATED_PRODUCT ?? "san-pham-lien-quan";
const RELATED_POSTS_SLUG = process.env.NEXT_PUBLIC_RELATED_POSTS ?? "bai-viet-lien-quan";

export {
	DEFAULT_CHANNEL,
	DEFAULT_CHANNEL_SLUG,
	DEFAULT_CHANNEL_PRODUCTS_SLUG,
	ALL_PRODUCTS_SLUG,
	RELATED_PRODUCT_SLUG,
	RELATED_POSTS_SLUG,
	PRODUCTS_SLUG
};
